plugins:
  activators:
    - themer.activators.wallfix.WallfixActivator
    - themer.activators.i3.I3Activator
    - themer.activators.termite.TermiteActivator
    - custom.CustomActivator
  parsers:
    - themer.ColorParser
files:

  i3.tpl: i3.conf
  powerline.tpl: colors.json
  termite.tpl: termite.conf

  # gtk stuff
  #gtk.tpl: gtk.css
  #gtkrc.tpl: gtkrc
  #menubarrc.tpl: menubar-toolbar-dark.rc
